<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NoteScribe.Core</RootNamespace>
    <AssemblyName>NoteScribe.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="NAudio.Core" />
    <PackageReference Include="NAudio.Wasapi" />
    <PackageReference Include="Anthropic" />
  </ItemGroup>

</Project>
