<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NoteScribe.Cli</RootNamespace>
    <AssemblyName>notescribe</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoteScribe.Core\NoteScribe.Core.csproj" />
  </ItemGroup>

</Project>
